### PR TITLE
Changed namespace to .Adapters.Rhinoceros

### LINKED ISSUE #62: Rhinoceros_Toolkit: Move all public classes and methods to 'Adapters' namespace
Please move all public classes/methods to the 'Adapters' namespace, similar to Robot. This is important from a UI point of view as otherwise we'll have a very long list of discipline+software namespaces once settings and other objects are added to other adapters.

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #62 

Changed following namespaces: 
- `BH.oM.Rhinoceros => BH.oM.Adapters.Rhinoceros`
- `BH.Engine.Rhinoceros => BH.Engine.Adapters.Rhinoceros`

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot fix project file ref. 20295565273

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot fix project file ref. 20296356735

**Comment by Tom-Kingstone** [comment]
@BHoMBot check project-compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Comment by Tom-Kingstone** [comment]
@BHoMBot check copyright-compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by FraserGreenroyd — APPROVED** [review]
Great work @Tom-Kingstone thanks for picking up this historic issue and closing it out, it's nice to see this align nicely to other toolkits. @alelom even gave a thumbs up so he's happy as well 😄

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
