### PR TITLE
Align to Graphics_oM `Vertex` to `RenderPoint` refactoring

### LINKED ISSUE #210: Align to Graphics_oM `Vertex` to `RenderPoint` refactoring
#### Broken rules:

See https://github.com/BHoM/BHoM/issues/1273

### PR DESCRIPTION
**Pull request by alelom**
### NOTE: Depends on 

BHoM/BHoM_Engine#2606
   
### Issues addressed by this PR

Closes #210

### CODE REVIEW

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by alelom** [comment]
@BHoMBot check required

**Review by enarhi — APPROVED** [review]
LGTM

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
