### PR TITLE
Adding ToRhino method for Texture

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1389
   
### Issues addressed by this PR

Adding ToRhino method for Texture, returning a rhino DisplayMaterial

### CODE REVIEW

**Review by michaelhoehn — DISMISSED** [review]
I've tested and approved this feature. LGTM!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: core, installer, versioning, project-compliance, code-compliance, documentation-compliance, serialisation, null-handling, copyright-compliance

**Review by FraserGreenroyd — APPROVED** [review]
Approving based on previous review from @michaelhoehn . Commits since that review have been 1 compliance, and 1 typo fixed in discussion with @IsakNaslundBh . Checks have been given neutral status as they passed on the commit prior to the typo fix which was the only change.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 6623389143

**Pull request merged**
